// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ollofrmjwmhivgceuvqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sbG9mcm1qd21oaXZnY2V1dnF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODMyNTQsImV4cCI6MjA2MTE1OTI1NH0.oK8-wYaN6iUmJeojNe01NMxQWrRv1OTj9_1f-226Jrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);